name: Rust CI Check

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    # - name: Run install_ospect.sh on Unix
    #   if: matrix.os != 'windows-latest'
    #   run: |
    #     chmod +x install_ospect.sh
    #     echo "y" | ./install_ospect.sh
    #     export PATH="$HOME/bin:$PATH"
    #     ospect --version

    - name: Run install_ospect.bat on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        echo.exe "y" | call .\install_ospect.bat
        ospect --version