name: Rust

on:
  push:
    branches: [ "main","scratch" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
