name: Rust

on:
  push:
    branches: [ "main","scratch" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Cargo Clean
      run: cargo clean
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
